### ISSUE TITLE
view.insertView(scrollView, at: 0) messing with layer transparency

### ISSUE THREAD

**Issue by Mapamatician** [ariok/BWWalkthrough#83]
Hi guys,

First off thanks for the awesome plugin.
I have a layer issue

On my BWWalkthroughViewController, I have a UIImageView with alpha 0.1 as a background that I want for all of the BWWalkthroughPageViewControllers

Each BWWalkthroughPageViewController has a UIImage with alpha 1.0, but these images are below the background image. How can I bring them to the front?

In viewDidLoad 
        view.insertSubview(scrollview, at: 0) //scrollview is inserted as first view of the hierarchy
If I change this to anything from 0 the layer won't appear

Hope someone can help,
Thanks

**Comment by ariok** [comment]
Probably the only way you have to achieve this result is subclassing `BWWalkthroughViewController` and implement your custom behaviour. Also, to set view transparency for a view controller view you have to deal with `opaque` property of the view http://stackoverflow.com/questions/8520434/uiview-opaque-vs-alpha-vs-opacity.

I close the issue since this is not really related to BWWalkthrough, it sounds more a "problem" with your custom implementation.
